from datetime import datetime
from decimal import Decimal
import json

import pytest
from pydantic import ValidationError
from sqlalchemy import create_engine, func, select
from sqlalchemy.orm import Session
from sqlalchemy.pool import StaticPool

from app.models import Base, Match, MatchPlayer, Player, Team
from app.report_schemas import ReportRequest, TacticalReportResponse
from app.report_service import (
    ReportValidationError,
    _insight_evidence_id,
    generate_tactical_report,
    validate_evidence_links,
)


def _payload(**updates):
    result = {
        "home_team_id": 1,
        "away_team_id": 2,
        "formation_by_side": {"home": "4-3-3", "away": "4-4-2"},
        "players": [
            {"player_id": 1, "side": "home", "formation_slot": 0, "position": {"x": 7, "y": 50}},
            {"player_id": 2, "side": "away", "formation_slot": 1, "position": {"x": 80, "y": 30}},
        ],
    }
    result.update(updates)
    return result


def _historical_side(team_id, team_name, opponent_id, opponent_name):
    team = {"id": team_id, "name": team_name}
    opponent = {"id": opponent_id, "name": opponent_name}
    metric = {"total": 12500.5, "mean_per_measured_player": 12500.5, "measured_player_count": 1}
    average = {
        "selected_team_average_total": 12500.5,
        "opponent_average_total": 11000.0,
        "selected_team_average_per_measured_player": 12500.5,
        "opponent_average_per_measured_player": 11000.0,
        "selected_minus_opponent_average_delta": 1500.5,
    }
    coverage = {"measured_player_appearances": 1, "player_appearances": 1, "percentage": 100.0}
    return {
        "team": team,
        "summary": {
            "match_count": 1,
            "results": {"wins": 1, "draws": 0, "losses": 0},
            "physical_averages": {"distance": average, "sprints": average},
            "measurement_coverage": {
                "distance": {"selected_team": coverage, "opponent": coverage},
                "sprints": {"selected_team": coverage, "opponent": coverage},
            },
        },
        "matches": [{
            "id": 10,
            "kickoff_at": "2026-01-01T15:00:00",
            "home_team": team,
            "away_team": opponent,
            "selected_team": team,
            "opponent": opponent,
            "venue_context": "home",
            "result": "win",
            "goals_for": 2,
            "goals_against": 1,
            "physical_comparison": {
                "selected_team": {"distance": metric, "sprints": metric},
                "opponent": {"distance": metric, "sprints": metric},
                "selected_minus_opponent": {"distance_total": 1500.5, "sprint_total": 3},
            },
            "players": [{
                "player_id": 5,
                "player_name": "Demo Player",
                "team_id": team_id,
                "distance_covered_meters": 12500.5,
                "sprint_count": 7,
            }],
        }],
    }


def _report_response_payload():
    return {
        "report_mode": "deterministic_mock",
        "data_label": "DEMO DATA — fictional examples",
        "report_notice": "Rule-based demonstration.",
        "scenario": {
            "home_team": {"id": 1, "name": "Home"},
            "away_team": {"id": 2, "name": "Away"},
            "formation_by_side": {"home": "4-3-3", "away": "4-4-2"},
            "placed_player_count": {"home": 1, "away": 1},
        },
        "executive_summary": "Demo summary.",
        "observations": [],
        "recommendations": [],
        "evidence_refs": [{
            "id": "scenario_metric:zone:0:0",
            "kind": "scenario_metric",
            "label": "Top left occupancy",
            "source_key": "zone_occupancy",
            "side": None,
            "team_id": None,
            "match_id": None,
            "player_id": None,
            "player_ids": [],
            "value": None,
        }],
        "relevant_player_ids": [],
        "historical_context": {
            "home": _historical_side(1, "Home", 2, "Away"),
            "away": _historical_side(2, "Away", 1, "Home"),
        },
        "limitations": [],
    }


def test_report_api_returns_evidence_linked_deterministic_report(client):
    first = client.post("/api/analysis/reports", json=_payload())
    second = client.post("/api/analysis/reports", json=_payload())
    assert first.status_code == second.status_code == 200
    report = first.json()
    assert report == second.json()
    assert report["report_mode"] == "deterministic_mock"
    assert "not generated by a real AI model" in report["report_notice"]
    assert report["scenario"]["placed_player_count"] == {"home": 1, "away": 1}
    references = {item["id"] for item in report["evidence_refs"]}
    assert all(set(item["evidence_ids"]) <= references for item in report["observations"])
    assert all(set(item["evidence_ids"]) <= references for item in report["recommendations"])
    assert all(item["id"].startswith("historical_match:") for item in report["evidence_refs"] if item["kind"] == "historical_match")
    assert all("." not in item["id"].split(":")[-1] for item in report["evidence_refs"] if item["kind"] == "scenario_metric")


@pytest.mark.parametrize("payload, expected", [
    (_payload(home_team_id=99), 404),
    (_payload(players=[{"player_id": 999, "side": "home", "formation_slot": 0, "position": {"x": 1, "y": 1}}]), 404),
    (_payload(home_team_id=1, away_team_id=1), 422),
    (_payload(players=[{"player_id": 2, "side": "home", "formation_slot": 0, "position": {"x": 1, "y": 1}}]), 422),
    (_payload(players=[
        {"player_id": 1, "side": "home", "formation_slot": 0, "position": {"x": 1, "y": 1}},
        {"player_id": 1, "side": "away", "formation_slot": 0, "position": {"x": 2, "y": 2}},
    ]), 422),
    (_payload(players=[
        {"player_id": 1, "side": "home", "formation_slot": 0, "position": {"x": 1, "y": 1}},
        {"player_id": 1, "side": "home", "formation_slot": 1, "position": {"x": 2, "y": 2}},
    ]), 422),
    (_payload(players=[{"player_id": 1, "side": "home", "formation_slot": 11, "position": {"x": 1, "y": 1}}]), 422),
    (_payload(formation_by_side={"home": "4-1-4-1", "away": "4-4-2"}), 422),
])
def test_request_identity_assignment_and_formation_errors(client, payload, expected):
    assert client.post("/api/analysis/reports", json=payload).status_code == expected


@pytest.mark.parametrize(("field", "value"), [
    ("home_team_id", True), ("home_team_id", "1"), ("home_team_id", 1.0), ("home_team_id", None),
    ("away_team_id", False), ("away_team_id", "2"), ("away_team_id", 2.0),
    ("player_id", False), ("player_id", "5"), ("player_id", 5.0), ("player_id", None),
    ("formation_slot", "3"), ("formation_slot", True), ("formation_slot", 3.0),
])
def test_http_request_identifiers_require_json_integers(client, field, value):
    payload = _payload()
    if field in {"home_team_id", "away_team_id"}:
        payload[field] = value
    else:
        payload["players"][0][field] = value

    response = client.post("/api/analysis/reports", json=payload)

    assert response.status_code == 422
    assert "Traceback" not in response.text
    assert "report_schemas.py" not in response.text


def test_two_different_players_cannot_occupy_the_same_formation_slot():
    engine = create_engine("sqlite://", poolclass=StaticPool)
    Base.metadata.create_all(engine)
    with Session(engine) as db:
        home, away = Team(name="Slot Home"), Team(name="Slot Away")
        db.add_all([home, away])
        db.flush()
        db.add_all([
            Player(team_id=home.id, name="Home One", position="Defender"),
            Player(team_id=home.id, name="Home Two", position="Defender"),
        ])
        db.flush()
        players = list(db.query(Player).order_by(Player.id))
        request = ReportRequest.model_validate({
            "home_team_id": home.id,
            "away_team_id": away.id,
            "formation_by_side": {"home": "4-3-3", "away": "4-4-2"},
            "players": [
                {"player_id": players[0].id, "side": "home", "formation_slot": 0, "position": {"x": 10, "y": 30}},
                {"player_id": players[1].id, "side": "home", "formation_slot": 0, "position": {"x": 20, "y": 60}},
            ],
        })
        with pytest.raises(ReportValidationError, match="formation slot"):
            generate_tactical_report(db, request)
    Base.metadata.drop_all(engine)
    engine.dispose()


def test_duplicate_player_names_keep_structural_evidence_ids():
    insight = {
        "category": "spatial_gap", "teamSide": "home",
        "playerIds": [92, 91], "players": ["Twin", "Twin"],
    }
    assert _insight_evidence_id(insight) == "scenario_insight:spatial_gap:home:91:92"


def test_report_renders_recommendations_from_validated_insight_claims_only():
    engine = create_engine("sqlite://", poolclass=StaticPool, connect_args={"check_same_thread": False})
    Base.metadata.create_all(engine)
    with Session(engine) as db:
        home, away = Team(id=1, name="Home Shape"), Team(id=2, name="Away Shape")
        db.add_all([home, away])
        db.flush()
        db.add_all([
            Player(id=1, team_id=1, name="Home Defender", position="Defender"),
            Player(id=2, team_id=1, name="Home Midfielder", position="Midfielder"),
            Player(id=3, team_id=2, name="Away Forward", position="Forward"),
        ])
        db.commit()
        request = ReportRequest.model_validate({
            "home_team_id": 1, "away_team_id": 2,
            "formation_by_side": {"home": "4-3-3", "away": "4-4-2"},
            "players": [
                {"player_id": 1, "side": "home", "formation_slot": 0, "position": {"x": 10, "y": 30}},
                {"player_id": 2, "side": "home", "formation_slot": 1, "position": {"x": 60, "y": 60}},
                {"player_id": 3, "side": "away", "formation_slot": 0, "position": {"x": 80, "y": 50}},
            ],
        })
        report = generate_tactical_report(db, request).model_dump(mode="json")
        assert report["recommendations"]
        for recommendation in report["recommendations"]:
            assert recommendation["claim"]["claim_type"] == "scenario_insight"
            assert recommendation["evidence_ids"] == [recommendation["claim"]["evidence_id"]]
            assert recommendation["id"] == f"recommendation:{recommendation['claim']['evidence_id']}"
            if recommendation["claim"]["category"] == "line_spacing":
                assert "Review Home Shape's current defensive-to-midfield separation" in recommendation["text"]
            else:
                assert recommendation["text"].startswith("Review ")

        class MetricProvider:
            def generate(self, context):
                value = context["metrics"]["home"]["widthMeters"]
                claim = {
                    "claim_type": "scenario_metric",
                    "evidence_id": "scenario_metric:home:width_meters",
                    "side": "home", "team_id": 1, "metric_key": "width_meters",
                    "player_ids": [], "value": value,
                }
                return {
                    "observations": [{"claim": claim, "confidence": "high"}],
                    "recommendations": [{"claim": claim}],
                }

        metric_report = generate_tactical_report(db, request, provider=MetricProvider()).model_dump(mode="json")
        assert metric_report["observations"][0]["claim"]["metric_key"] == "width_meters"
        assert "pitch width" in metric_report["recommendations"][0]["text"]
    Base.metadata.drop_all(engine)
    engine.dispose()


@pytest.mark.parametrize("position", [
    {"x": -0.01, "y": 50}, {"x": 100.01, "y": 50}, {"x": 50, "y": -0.01},
    {"x": 50, "y": 100.01}, {"x": None, "y": 10},
])
def test_positions_must_be_finite_and_within_inclusive_pitch_bounds(client, position):
    payload = _payload(players=[
        {"player_id": 1, "side": "home", "formation_slot": 0, "position": position},
    ])
    response = client.post(
        "/api/analysis/reports",
        content=json.dumps(payload, allow_nan=True),
        headers={"Content-Type": "application/json"},
    )
    assert response.status_code == 422


@pytest.mark.parametrize("position", [{"x": float("nan"), "y": 10}, {"x": 10, "y": float("inf")}])
def test_schema_rejects_nonfinite_coordinates(position):
    with pytest.raises(ValidationError):
        ReportRequest.model_validate({
            "home_team_id": 1,
            "away_team_id": 2,
            "formation_by_side": {"home": "4-3-3", "away": "4-4-2"},
            "players": [{"player_id": 1, "side": "home", "formation_slot": 0, "position": position}],
        })


def test_empty_and_partial_formations_are_valid(client):
    empty = client.post("/api/analysis/reports", json=_payload(players=[]))
    assert empty.status_code == 200
    assert empty.json()["scenario"]["placed_player_count"] == {"home": 0, "away": 0}
    partial = client.post("/api/analysis/reports", json=_payload(players=[
        {"player_id": 1, "side": "home", "formation_slot": 10, "position": {"x": 0, "y": 100}},
    ]))
    assert partial.status_code == 200


def _claim_evidence():
    return {
        "scenario_insight:line_spacing:home:defenseToMidfield": {
            "id": "scenario_insight:line_spacing:home:defenseToMidfield",
            "kind": "scenario_insight", "source_key": "line_spacing",
            "side": "home", "team_id": 1, "player_ids": [],
            "value": {
                "category": "line_spacing", "teamSide": "home", "playerIds": [],
                "relatedMetric": {"key": "defenseToMidfield", "value": 19.5},
                "description": "Home defensive-to-midfield separation is 19.5m.",
            },
        },
        "scenario_metric:home:width_meters": {
            "id": "scenario_metric:home:width_meters", "kind": "scenario_metric",
            "source_key": "width_meters", "side": "home", "team_id": 1,
            "player_ids": [], "value": 42.0,
        },
        "historical_match:10:team:1": {
            "id": "historical_match:10:team:1", "kind": "historical_match",
            "team_id": 1, "match_id": 10,
            "value": {"result": "win", "goals_for": 2, "goals_against": 1, "kickoff_at": "2026-01-01T15:00:00"},
        },
        "historical_measurement:10:7:distance_covered_meters": {
            "id": "historical_measurement:10:7:distance_covered_meters",
            "kind": "historical_measurement", "team_id": 1, "match_id": 10,
            "player_id": 7, "source_key": "distance_covered_meters", "value": 12345.5,
        },
        "scenario_insight:spatial_gap:home:5:6": {
            "id": "scenario_insight:spatial_gap:home:5:6",
            "kind": "scenario_insight", "source_key": "spatial_gap",
            "side": "home", "team_id": 1, "player_ids": [5, 6],
            "value": {
                "category": "spatial_gap", "teamSide": "home", "playerIds": [5, 6],
                "relatedMetric": {"key": "spatialGapDistance", "value": 31.0},
                "players": ["Player Five", "Player Six"],
                "description": "Home spatial gap: Player Five ↔ Player Six — 31.0m.",
            },
        },
    }


def _insight_claim(evidence_id="scenario_insight:line_spacing:home:defenseToMidfield"):
    return {
        "claim_type": "scenario_insight", "evidence_id": evidence_id,
        "side": "home", "team_id": 1, "category": "line_spacing",
        "player_ids": [], "metric_key": "defenseToMidfield", "value": 19.5,
        "zone_row": None, "zone_column": None,
    }


def _valid_claim_report():
    return {
        "observations": [
            {"claim": _insight_claim(), "confidence": "high"},
            {"claim": {
                "claim_type": "scenario_metric", "evidence_id": "scenario_metric:home:width_meters",
                "side": "home", "team_id": 1, "metric_key": "width_meters",
                "player_ids": [], "value": 42.0,
            }, "confidence": "high"},
            {"claim": {
                "claim_type": "historical_measurement",
                "evidence_id": "historical_measurement:10:7:distance_covered_meters",
                "team_id": 1, "match_id": 10, "player_id": 7,
                "metric_field": "distance_covered_meters", "value": 12345.5,
            }, "confidence": "high"},
        ],
        "recommendations": [
            {"claim": _insight_claim()},
            {"claim": {
                "claim_type": "scenario_metric", "evidence_id": "scenario_metric:home:width_meters",
                "side": "home", "team_id": 1, "metric_key": "width_meters",
                "player_ids": [], "value": 42.0,
            }},
        ],
    }


def test_valid_structured_observations_and_recommendations_match_their_evidence():
    validated = validate_evidence_links(_valid_claim_report(), _claim_evidence())
    assert len(validated.observations) == 3
    assert len(validated.recommendations) == 2


def test_typed_historical_context_preserves_payload_shape_and_optional_null_ids():
    payload = _report_response_payload()

    report = TacticalReportResponse.model_validate(payload)

    assert report.model_dump() == payload
    assert report.historical_context["home"].team.id == 1
    assert report.historical_context["home"].summary.results.model_dump() == {"wins": 1, "draws": 0, "losses": 0}
    assert report.historical_context["home"].matches[0].physical_comparison.selected_team.distance.measured_player_count == 1
    assert report.historical_context["home"].matches[0].players[0].distance_covered_meters == 12500.5
    assert report.evidence_refs[0].team_id is None
    assert report.evidence_refs[0].match_id is None
    assert report.evidence_refs[0].player_id is None


def _set_nested_value(value, path, replacement):
    current = value
    for part in path[:-1]:
        current = current[part]
    current[path[-1]] = replacement


@pytest.mark.parametrize(("path", "value"), [
    (("home", "team", "id"), True),
    (("home", "team", "id"), None),
    (("home", "matches", 0, "id"), "10"),
    (("home", "matches", 0, "home_team", "id"), 10.0),
    (("home", "matches", 0, "players", 0, "player_id"), "5"),
    (("away", "matches", 0, "players", 0, "team_id"), False),
])
def test_historical_context_rejects_malformed_nested_identifiers(path, value):
    payload = _report_response_payload()
    _set_nested_value(payload["historical_context"], path, value)

    with pytest.raises(ValidationError):
        TacticalReportResponse.model_validate(payload)


@pytest.mark.parametrize("player_ids", [["5"], [True], [5.0]])
def test_report_response_rejects_malformed_identifier_values_inside_lists(player_ids):
    payload = _report_response_payload()
    payload["evidence_refs"][0]["player_ids"] = player_ids

    with pytest.raises(ValidationError):
        TacticalReportResponse.model_validate(payload)


def test_historical_response_models_reject_unexpected_fields():
    mutations = [
        lambda payload: payload["historical_context"]["home"]["matches"][0].update({"unexpected": "value"}),
        lambda payload: payload["historical_context"]["home"]["summary"]["results"].update({"extra": 2}),
        lambda payload: payload["historical_context"]["home"]["summary"]["measurement_coverage"].update({"extra": {}}),
    ]
    for mutate in mutations:
        payload = _report_response_payload()
        mutate(payload)
        with pytest.raises(ValidationError):
            TacticalReportResponse.model_validate(payload)


@pytest.mark.parametrize("mutate, message", [
    (lambda report: report["observations"][0].update({"claim": {
        "claim_type": "scenario_metric", "evidence_id": "scenario_metric:home:width_meters",
        "side": "home", "team_id": 1, "metric_key": "line_spacing_defenseToMidfield",
        "player_ids": [], "value": 19.5,
    }}), "match its referenced evidence"),
    (lambda report: report["recommendations"][0]["claim"].update({"value": 8}), "match its referenced evidence"),
    (lambda report: report["observations"][0]["claim"].update({"team_id": 2}), "match its referenced evidence"),
    (lambda report: report["observations"][2]["claim"].update({"player_id": 8}), "match its referenced evidence"),
    (lambda report: report["observations"][2]["claim"].update({"match_id": 11}), "match its referenced evidence"),
    (lambda report: report["observations"][2]["claim"].update({"metric_field": "sprint_count"}), "match its referenced evidence"),
    (lambda report: report["observations"][0]["claim"].update({"evidence_id": "unknown"}), "unknown evidence"),
    (lambda report: report["observations"][0].update({"text": "The home team will win."}), "structured claims only"),
    (lambda report: report["observations"][0].update({"scope": "historical_context"}), "structured claims only"),
])
def test_unrelated_or_unsupported_claims_are_rejected(mutate, message):
    report = _valid_claim_report()
    mutate(report)
    with pytest.raises(ReportValidationError, match=message):
        validate_evidence_links(report, _claim_evidence())


@pytest.mark.parametrize(("claim_kind", "field", "value"), [
    ("scenario_metric", "team_id", True),
    ("scenario_metric", "team_id", "1"),
    ("scenario_metric", "team_id", 1.0),
    ("historical_measurement", "player_id", False),
    ("historical_measurement", "player_id", "5"),
    ("historical_measurement", "player_id", 5.0),
    ("historical_measurement", "match_id", "1"),
    ("historical_measurement", "match_id", 1.0),
    ("scenario_insight", "player_ids", ["5", 6]),
    ("scenario_insight", "player_ids", [True, 6]),
    ("scenario_insight", "player_ids", [5.0, 6]),
])
def test_provider_claim_identifiers_require_strict_integers(claim_kind, field, value):
    if claim_kind == "scenario_metric":
        claim = _valid_claim_report()["observations"][1]["claim"]
    elif claim_kind == "historical_measurement":
        claim = _valid_claim_report()["observations"][2]["claim"]
    else:
        claim = {
            "claim_type": "scenario_insight",
            "evidence_id": "scenario_insight:spatial_gap:home:5:6",
            "side": "home", "team_id": 1, "category": "spatial_gap",
            "player_ids": [5, 6], "metric_key": "spatialGapDistance", "value": 31.0,
            "zone_row": None, "zone_column": None,
        }
    claim[field] = value
    report = {"observations": [{"claim": claim, "confidence": "high"}], "recommendations": []}

    with pytest.raises(ReportValidationError, match="structured claims only") as error:
        validate_evidence_links(report, _claim_evidence())
    assert "Traceback" not in str(error.value)
    assert "report_schemas.py" not in str(error.value)


def test_report_is_deterministic_and_does_not_persist_rows():
    engine = create_engine("sqlite://", poolclass=StaticPool, connect_args={"check_same_thread": False})
    Base.metadata.create_all(engine)
    with Session(engine) as db:
        home, away = Team(id=1, name="Home Demo"), Team(id=2, name="Away Demo")
        db.add_all([home, away])
        db.flush()
        db.add_all([
            Player(id=1, team_id=1, name="Home Player", position="Defender"),
            Player(id=2, team_id=2, name="Away Player", position="Forward"),
        ])
        db.flush()
        db.add_all([
            Match(id=1, home_team_id=1, away_team_id=2, kickoff_at=datetime(2026, 1, 1), home_score=1, away_score=0),
            Match(id=2, home_team_id=1, away_team_id=2, kickoff_at=datetime(2026, 2, 1)),
            MatchPlayer(match_id=1, player_id=1, team_id=1, distance_covered_meters=Decimal("12345.50"), sprint_count=7),
            MatchPlayer(match_id=1, player_id=2, team_id=2, distance_covered_meters=Decimal("11000.00"), sprint_count=4),
        ])
        db.commit()
        models = (Team, Player, Match, MatchPlayer)
        before = {model.__tablename__: db.scalar(select(func.count()).select_from(model)) for model in models}
        request = ReportRequest.model_validate(_payload())
        first = generate_tactical_report(db, request).model_dump(mode="json")
        second = generate_tactical_report(db, request).model_dump(mode="json")
        after = {model.__tablename__: db.scalar(select(func.count()).select_from(model)) for model in models}
        assert first == second
        assert before == after
        validated_report = TacticalReportResponse.model_validate(first)
        assert validated_report.historical_context["home"].summary.match_count == 1
        assert validated_report.historical_context["home"].summary.results.model_dump() == {"wins": 1, "draws": 0, "losses": 0}
        completed = next(match for match in validated_report.historical_context["home"].matches if match.result is not None)
        assert completed.result == "win"
        assert (completed.goals_for, completed.goals_against) == (1, 0)
        assert completed.physical_comparison.selected_team.distance.total == 12345.5
        assert completed.physical_comparison.selected_team.distance.measured_player_count == 1
        assert completed.players[0].distance_covered_meters == 12345.5
        pending = next(match for match in first["historical_context"]["home"]["matches"] if match["result"] is None)
        assert pending["result"] is None
        assert any(
            item["scope"] == "historical_context"
            and item["claim"]["claim_type"] == "historical_match"
            and item["claim"]["match_id"] == pending["id"]
            and "pending; no result is classified" in item["text"]
            for item in first["observations"]
        )
        measurement = next(
            item for item in first["evidence_refs"]
            if item["kind"] == "historical_measurement" and item["player_id"] == 1
            and item["source_key"] == "distance_covered_meters"
        )
        assert measurement["value"] == 12345.5
        measurement_observation = next(
            item for item in first["observations"] if measurement["id"] in item["evidence_ids"]
        )
        assert measurement_observation["claim"]["player_id"] == 1
        assert measurement_observation["claim"]["metric_field"] == "distance_covered_meters"
        assert measurement_observation["claim"]["value"] == 12345.5
        assert "12345.5 m" in measurement_observation["text"]
    Base.metadata.drop_all(engine)
    engine.dispose()


def test_unexpected_server_errors_are_sanitized(client, monkeypatch):
    from app import report_routes

    def fail(*_args, **_kwargs):
        raise RuntimeError("internal secret must not be returned")

    monkeypatch.setattr(report_routes, "generate_tactical_report", fail)
    response = client.post("/api/analysis/reports", json=_payload())
    assert response.status_code == 500
    assert response.json() == {"detail": "Tactical report could not be generated"}
    assert "secret" not in response.text
